# CachyOS linux-cgroup-always – auto-persist P/E core profile
# Install to: /usr/share/fish/vendor_conf.d/30-cgterm-14700kf-profile.fish
#
# Runs once on the first interactive login.  Detects the P/E split,
# writes a persistent local profile, and is a no-op on every
# subsequent session (the local profile is sourced and the guard
# below exits early).
if not status --is-interactive
    return 0
end
if not functions -q cgterm_autoprofile_by_capacity
    return 0
end
set -l local_profile ~/.config/fish/conf.d/cgterm-local-profile.fish
if test -r "$local_profile"
    source "$local_profile" 2>/dev/null
end
if set -q CGTERM_PERFORMANCE_CPUS; and set -q CGTERM_POWERSAVE_CPUS
    return 0
end
cgterm_autoprofile_by_capacity >/dev/null 2>&1
if set -q CGTERM_PERFORMANCE_CPUS; and set -q CGTERM_POWERSAVE_CPUS
    mkdir -p ~/.config/fish/conf.d
    set -l perf (string escape --style=script -- "$CGTERM_PERFORMANCE_CPUS")
    set -l pwr  (string escape --style=script -- "$CGTERM_POWERSAVE_CPUS")
    printf '%s\n' \
      "# Auto-generated by linux-cgroup-always-fish" \
      "set -gx CGTERM_PERFORMANCE_CPUS $perf" \
      "set -gx CGTERM_POWERSAVE_CPUS $pwr" \
      > "$local_profile"
end
