# Auto-persist 14700KF profile on first interactive fish session.
# Safe no-op if profile is already defined.

if not status --is-interactive
    exit
end

if not functions -q cgterm_autoprofile_by_capacity
    exit
end

set -l local_profile ~/.config/fish/conf.d/cgterm-local-profile.fish

if test -r "$local_profile"
    source "$local_profile" 2>/dev/null
end

if set -q CGTERM_PERFORMANCE_CPUS; and set -q CGTERM_POWERSAVE_CPUS
    exit
end

cgterm_autoprofile_by_capacity >/dev/null 2>&1

if set -q CGTERM_PERFORMANCE_CPUS; and set -q CGTERM_POWERSAVE_CPUS
    mkdir -p ~/.config/fish/conf.d
    set -l perf (string escape --style=script -- "$CGTERM_PERFORMANCE_CPUS")
    set -l pwr  (string escape --style=script -- "$CGTERM_POWERSAVE_CPUS")

    printf "%s\n" \
      "# Auto-generated by linux-cgroup-always-fish" \
      "set -gx CGTERM_PERFORMANCE_CPUS $perf" \
      "set -gx CGTERM_POWERSAVE_CPUS $pwr" \
      > "$local_profile"
end
